### PR TITLE
Add bond orders

### PR DESCRIPTION
**Pull request by kimt33**
What:
1. Move functions into classes to avoid repeating code
2. Add normal bond orders
3. Add Wiberg-Mayer bond order
4. Add porcelain
5. Update according to changes

Issues
I think that the normal bond order is broken because the notes are wrong. I think that the weights are not normalized.

### CODE REVIEW

**Comment by FarnazH** [comment]
Thanks @kimt33. I just realized the `h2o_coeff_ab_mo_alpha.npy` is missing. Can you please add it?

**Comment by kimt33** [comment]
I've added the files, but there are more problems with the code.

I don't think I'll be able to pass the linters because the pycodestyle complaining about W503 (linebreak before binary operator) and W504 (linebreak after binary operator). The if statement is too long, but cannot be broken into separate lines without getting creative. I can also change the names of the variables to something shorter, but that would take away from the readability, I think. I can get creative with it, but it won't look pretty.

The method `OrbitalPartitionTools.bond_order`(line 514 of partition.py) is currently not implemented. There was a missing normalization constant in the notes when it was being implemented and was put on hold until it gets fixed. Honestly, I don't remember what was wrong with the derivation in the first place, or if it is really wrong. But it's currently not implemented. The test is missing a comparison with a reference too.

**Comment by kimt33** [comment]
I fixed the bond order code (I think). I used the equation from this article: https://onlinelibrary.wiley.com/doi/abs/10.1002/qua.560260111?casa_token=ChlQdhoiD9sAAAAA:MHeOVChsmkTtTt89BfEq-iWnXd5H5yQS0OrwecX5sq2_nlLDd-_c0prkDrC_G4JAIg3K_iIJtjQb2s8
 https://doi.org/10.1002/qua.560260111

**Comment by FarnazH** [comment]
Thanks @kimt33 for the update and taking the time to refresh the code. There is some major refactoring going on, so I will merge what you have in the `dev` branch and move on from there, so I wouldn't worry too much about `linter`'s errors.

**Comment by FarnazH** [comment]
These commits are merged into `dev` branch to be merged into `master` when things are more stable. So, I am closing this PR. Thanks.

**Pull request closed without merging**
